import os
from typing import List
from dotenv import load_dotenv
from langchain_core.documents import Document
from langchain_google_genai import GoogleGenerativeAIEmbeddings

# Ensure you have installed: pip install langchain-chroma
from langchain_chroma import Chroma 

# Load environment variables (specifically GOOGLE_API_KEY from your .env file)
load_dotenv()

# Define where the local database will be saved
CHROMA_PATH = "chroma_db"
COLLECTION_NAME = "ai_tutor_syllabus"

def create_vector_store(chunks: List[Document]) -> Chroma:
    """
    Embeds document chunks using Gemini and saves them in a local, persistent ChromaDB.
    
    Args:
        chunks (List[Document]): The text chunks generated by the document parser.
        
    Returns:
        Chroma: The initialized and populated vector store.
    """
    # 1. Verify API Key
    if not os.environ.get("GOOGLE_API_KEY"):
        raise ValueError("GOOGLE_API_KEY not found. Please ensure it is set in your .env file.")

    print("Initializing Google Gemini Embeddings (gemini-embedding-2-preview)...")
    
    # Initialize the Gemini embedding model
    # gemini-embedding-2-preview maps text into a highly accurate embedding space
    embeddings = GoogleGenerativeAIEmbeddings(model="gemini-embedding-2-preview")

    print(f"Embedding {len(chunks)} chunks and saving to local database at '{CHROMA_PATH}'...")
    
    # 2. Create and persist the vector database
    vector_store = Chroma.from_documents(
        documents=chunks,
        embedding=embeddings,
        persist_directory=CHROMA_PATH,
        collection_name=COLLECTION_NAME
    )
    
    print("Vector store successfully built and saved to disk!")
    return vector_store

def get_vector_store() -> Chroma:
    """
    Loads the existing local ChromaDB instance for querying.
    Used by the RAG engine to search without needing to re-embed documents.
    """
    embeddings = GoogleGenerativeAIEmbeddings(model="gemini-embedding-2-preview")
    
    # Load the existing database from the local directory
    return Chroma(
        persist_directory=CHROMA_PATH,
        embedding_function=embeddings,
        collection_name=COLLECTION_NAME
    )



# # --- Testing the pipeline locally ---
# if __name__ == "__main__":
#     try:
#         from document_parser import load_and_chunk_pdf
#     except ImportError:
#         print("Make sure this is in the same directory as document_parser.py")
#         exit(1)

#     sample_pdf_path = os.path.join("data_samples", "SEM-2 PRES.pdf")
    
#     if not os.path.exists(sample_pdf_path):
#         print(f"Cannot run test. Please place a real PDF at: {os.path.abspath(sample_pdf_path)}")
#     else:
#         try:
#             print("--- Starting Document Ingestion Pipeline ---")
#             chunks = load_and_chunk_pdf(sample_pdf_path)
            
#             if chunks:
#                 db = create_vector_store(chunks)
#                 print("\nPipeline Test Complete. Check your project root for the 'chroma_db' folder.")
#         except Exception as e:
#             print(f"An error occurred during vector store creation: {e}")